import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  const users = [
    {
      username: "Alice",
      email: "alice@example.com",
      password: "Alic3@789",
      anonymous: true,
    },
    {
      username: "Bob",
      email: "bob@example.com",
      password: "B0b!pass",
      anonymous: false,
    },
    {
      username: "Charlie",
      email: "charlie@example.com",
      password: "Charl13#22",
      anonymous: true,
    },
    {
      username: "David",
      email: "david@example.com",
      password: "Dav!d456",
      anonymous: false,
    },
    {
      username: "Eva",
      email: "eva@example.com",
      password: "Ev@2024",
      anonymous: true,
    },
    {
      username: "Frank",
      email: "frank@example.com",
      password: "Fr@nk#888",
      anonymous: false,
    },
    {
      username: "Grace",
      email: "grace@example.com",
      password: "Gr@cE!12",
      anonymous: true,
    },
    {
      username: "Hannah",
      email: "hannah@example.com",
      password: "H@nn@h23",
      anonymous: false,
    },
    {
      username: "Ivy",
      email: "ivy@example.com",
      password: "1vy!cool",
      anonymous: true,
    },
    {
      username: "Jack",
      email: "jack@example.com",
      password: "J@ck1234",
      anonymous: false,
    },
    {
      username: "Kara",
      email: "kara@example.com",
      password: "K@ra4567",
      anonymous: true,
    },
    {
      username: "Liam",
      email: "liam@example.com",
      password: "L!am2025",
      anonymous: false,
    },
    {
      username: "Mia",
      email: "mia@example.com",
      password: "M!a987",
      anonymous: true,
    },
    {
      username: "Nina",
      email: "nina@example.com",
      password: "N!n@333",
      anonymous: false,
    },
    {
      username: "Oscar",
      email: "oscar@example.com",
      password: "Osc@r!11",
      anonymous: true,
    },
    {
      username: "Paul",
      email: "paul@example.com",
      password: "P@ul#777",
      anonymous: false,
    },
    {
      username: "Quinn",
      email: "quinn@example.com",
      password: "Qu!nn009",
      anonymous: true,
    },
    {
      username: "Riley",
      email: "riley@example.com",
      password: "R!ley#22",
      anonymous: false,
    },
    {
      username: "Sophie",
      email: "sophie@example.com",
      password: "Soph!e2023",
      anonymous: true,
    },
    {
      username: "Tom",
      email: "tom@example.com",
      password: "T0m@234",
      anonymous: false,
    },
    {
      username: "Uma",
      email: "uma@example.com",
      password: "Um@12345",
      anonymous: true,
    },
    {
      username: "Vera",
      email: "vera@example.com",
      password: "V3r@Pass",
      anonymous: false,
    },
    {
      username: "Will",
      email: "will@example.com",
      password: "W!ll7890",
      anonymous: true,
    },
    {
      username: "Xander",
      email: "xander@example.com",
      password: "X@nd#55",
      anonymous: false,
    },
    {
      username: "Yara",
      email: "yara@example.com",
      password: "Y@ra456",
      anonymous: true,
    },
    {
      username: "Zane",
      email: "zane@example.com",
      password: "Z@ne321",
      anonymous: false,
    },
    {
      username: "Anna",
      email: "anna@example.com",
      password: "Ann@Cool",
      anonymous: true,
    },
    {
      username: "Ben",
      email: "ben@example.com",
      password: "B3n!pass",
      anonymous: false,
    },
    {
      username: "Clara",
      email: "clara@example.com",
      password: "Cl@rA2024",
      anonymous: true,
    },
    {
      username: "Dylan",
      email: "dylan@example.com",
      password: "Dyl@n789",
      anonymous: false,
    },
    {
      username: "Ella",
      email: "ella@example.com",
      password: "El!a123",
      anonymous: true,
    },
    {
      username: "Felix",
      email: "felix@example.com",
      password: "Fel!x567",
      anonymous: false,
    },
    {
      username: "Gina",
      email: "gina@example.com",
      password: "G!na456",
      anonymous: true,
    },
    {
      username: "Harry",
      email: "harry@example.com",
      password: "H@rry!321",
      anonymous: false,
    },
    {
      username: "Isla",
      email: "isla@example.com",
      password: "Is!a009",
      anonymous: true,
    },
    {
      username: "James",
      email: "james@example.com",
      password: "Jam3s@77",
      anonymous: false,
    },
    {
      username: "Kim",
      email: "kim@example.com",
      password: "K!mPass",
      anonymous: true,
    },
    {
      username: "Luca",
      email: "luca@example.com",
      password: "Luc@2345",
      anonymous: false,
    },
    {
      username: "Maya",
      email: "maya@example.com",
      password: "M@y@Cool",
      anonymous: true,
    },
    {
      username: "Noah",
      email: "noah@example.com",
      password: "N0@h!123",
      anonymous: false,
    },
    {
      username: "Olivia",
      email: "olivia@example.com",
      password: "Ol!v!a789",
      anonymous: true,
    },
    {
      username: "Perry",
      email: "perry@example.com",
      password: "P3rry!22",
      anonymous: false,
    },
    {
      username: "Quincy",
      email: "quincy@example.com",
      password: "Qu!ncY77",
      anonymous: true,
    },
    {
      username: "Rita",
      email: "rita@example.com",
      password: "R!t@007",
      anonymous: false,
    },
    {
      username: "Sam",
      email: "sam@example.com",
      password: "S@m9876",
      anonymous: true,
    },
    {
      username: "Tina",
      email: "tina@example.com",
      password: "T!na!2023",
      anonymous: false,
    },
    {
      username: "Uri",
      email: "uri@example.com",
      password: "Ur!2024",
      anonymous: true,
    },
    {
      username: "Vince",
      email: "vince@example.com",
      password: "V!nc3Pass",
      anonymous: false,
    },
    {
      username: "Wendy",
      email: "wendy@example.com",
      password: "W3ndy!@#",
      anonymous: true,
    },
    {
      username: "Xena",
      email: "xena@example.com",
      password: "X3n@Cool",
      anonymous: false,
    },
    {
      username: "Yvonne",
      email: "yvonne@example.com",
      password: "Yv0nn3#1",
      anonymous: true,
    },
    {
      username: "Zach",
      email: "zach@example.com",
      password: "Z@ch!123",
      anonymous: false,
    },
    {
      username: "Ava",
      email: "ava@example.com",
      password: "Av@234",
      anonymous: true,
    },
    {
      username: "Brian",
      email: "brian@example.com",
      password: "Br!@n456",
      anonymous: false,
    },
    {
      username: "Catherine",
      email: "catherine@example.com",
      password: "C@th!R!n3",
      anonymous: true,
    },
    {
      username: "Daniel",
      email: "daniel@example.com",
      password: "D@n!el2024",
      anonymous: false,
    },
    {
      username: "Emma",
      email: "emma@example.com",
      password: "Emm@Pass",
      anonymous: true,
    },
    {
      username: "Finn",
      email: "finn@example.com",
      password: "F!nn@23",
      anonymous: false,
    },
    {
      username: "Grace",
      email: "grace@example.com",
      password: "Gr@ce!11",
      anonymous: true,
    },
    {
      username: "Henry",
      email: "henry@example.com",
      password: "H3nry#22",
      anonymous: false,
    },
    {
      username: "Isabella",
      email: "isabella@example.com",
      password: "Is@b3ll@!",
      anonymous: true,
    },
    {
      username: "Jack",
      email: "jack@example.com",
      password: "J@ck2025",
      anonymous: false,
    },
    {
      username: "Kathy",
      email: "kathy@example.com",
      password: "K@thy!23",
      anonymous: true,
    },
    {
      username: "Liam",
      email: "liam@example.com",
      password: "L!@m321",
      anonymous: false,
    },
    {
      username: "Mia",
      email: "mia@example.com",
      password: "M!a@Cool",
      anonymous: true,
    },
    {
      username: "Nathan",
      email: "nathan@example.com",
      password: "N@th@n2023",
      anonymous: false,
    },
    {
      username: "Olivia",
      email: "olivia@example.com",
      password: "Ol!v#22",
      anonymous: true,
    },
    {
      username: "Patrick",
      email: "patrick@example.com",
      password: "P@tr1ck!",
      anonymous: false,
    },
    {
      username: "Quinn",
      email: "quinn@example.com",
      password: "Qu!nn567",
      anonymous: true,
    },
    {
      username: "Rachael",
      email: "rachael@example.com",
      password: "R@ch#123",
      anonymous: false,
    },
    {
      username: "Sarah",
      email: "sarah@example.com",
      password: "S@r@h456",
      anonymous: true,
    },
    {
      username: "Tom",
      email: "tom@example.com",
      password: "T0m!Cool",
      anonymous: false,
    },
    {
      username: "Ursula",
      email: "ursula@example.com",
      password: "Ursul@77",
      anonymous: true,
    },
    {
      username: "Vera",
      email: "vera@example.com",
      password: "V3r@#888",
      anonymous: false,
    },
    {
      username: "Will",
      email: "will@example.com",
      password: "W!ll!111",
      anonymous: true,
    },
    {
      username: "Xander",
      email: "xander@example.com",
      password: "X@ndr#22",
      anonymous: false,
    },
    {
      username: "Yara",
      email: "yara@example.com",
      password: "Y@rA007",
      anonymous: true,
    },
    {
      username: "Zane",
      email: "zane@example.com",
      password: "Z@ne!44",
      anonymous: false,
    },
    {
      username: "Alice2",
      email: "alice2@example.com",
      password: "AliC3#555",
      anonymous: true,
    },
    {
      username: "Ben2",
      email: "ben2@example.com",
      password: "B3n2@Pass",
      anonymous: false,
    },
    {
      username: "Clara2",
      email: "clara2@example.com",
      password: "Cl@rA2#!",
      anonymous: true,
    },
    {
      username: "David2",
      email: "david2@example.com",
      password: "D@v!d999",
      anonymous: false,
    },
    {
      username: "Eva2",
      email: "eva2@example.com",
      password: "Ev@2Cool",
      anonymous: true,
    },
    {
      username: "Frank2",
      email: "frank2@example.com",
      password: "Fr@nk2024",
      anonymous: false,
    },
    {
      username: "Grace2",
      email: "grace2@example.com",
      password: "Gr@ce#2",
      anonymous: true,
    },
    {
      username: "Hannah2",
      email: "hannah2@example.com",
      password: "H@nn@h2",
      anonymous: false,
    },
    {
      username: "Ivy2",
      email: "ivy2@example.com",
      password: "IvY!2023",
      anonymous: true,
    },
    {
      username: "Jack2",
      email: "jack2@example.com",
      password: "J@ck2Cool",
      anonymous: false,
    },
    {
      username: "Kara2",
      email: "kara2@example.com",
      password: "K@r@2024",
      anonymous: true,
    },
    {
      username: "Liam2",
      email: "liam2@example.com",
      password: "L!am2@22",
      anonymous: false,
    },
    {
      username: "Mia2",
      email: "mia2@example.com",
      password: "M!a2#11",
      anonymous: true,
    },
    {
      username: "Nina2",
      email: "nina2@example.com",
      password: "N!n@2025",
      anonymous: false,
    },
    {
      username: "Oscar2",
      email: "oscar2@example.com",
      password: "Osc@r2!",
      anonymous: true,
    },
    {
      username: "Paul2",
      email: "paul2@example.com",
      password: "P@ul2#22",
      anonymous: false,
    },
    {
      username: "Quinn2",
      email: "quinn2@example.com",
      password: "Qu!nn2@!",
      anonymous: true,
    },
    {
      username: "Riley2",
      email: "riley2@example.com",
      password: "R!l3y2024",
      anonymous: false,
    },
    {
      username: "Sophie2",
      email: "sophie2@example.com",
      password: "S0ph!e2#",
      anonymous: true,
    },
    {
      username: "Tom2",
      email: "tom2@example.com",
      password: "T0m2!Ok",
      anonymous: false,
    },
    {
      username: "Uma2",
      email: "uma2@example.com",
      password: "Um@2!cool",
      anonymous: true,
    },
    {
      username: "Vera2",
      email: "vera2@example.com",
      password: "V3ra2#2024",
      anonymous: false,
    },
  ];

  const confessions = [
    {
      message: "Você é meu sorriso preferido.",
      message_type: "Romântica",
      recipient: 87,
      sender: 1,
    },
    {
      message: "Sua amizade ilumina meus dias.",
      message_type: "Amizade",
      recipient: 14,
      sender: 2,
    },
    {
      message: "Acredite na sua força. Ela é maior do que você pensa.",
      message_type: "Motivacional",
      recipient: 55,
      sender: 3,
    },
    {
      message: "A vida é cheia de momentos lindos e você é um deles.",
      message_type: "Romântica",
      recipient: 33,
      sender: 4,
    },
    {
      message: "Fica a dica: você arrasa!",
      message_type: "Motivacional",
      recipient: 63,
      sender: 5,
    },
    {
      message: "Sua risada é meu remédio favorito.",
      message_type: "Amizade",
      recipient: 12,
      sender: 6,
    },
    {
      message: "Eu admiro sua coragem, sempre!",
      message_type: "Motivacional",
      recipient: 22,
      sender: 7,
    },
    {
      message: "Amigos como você são raros de encontrar.",
      message_type: "Amizade",
      recipient: 47,
      sender: 8,
    },
    {
      message: "Seja sempre quem você é. Não existe ninguém igual.",
      message_type: "Motivacional",
      recipient: 29,
      sender: 9,
    },
    {
      message: "Você é uma inspiração para todos ao seu redor.",
      message_type: "Motivacional",
      recipient: 72,
      sender: 10,
    },
    {
      message: "A vida é melhor com você nela.",
      message_type: "Romântica",
      recipient: 18,
      sender: 11,
    },
    {
      message: "Estou tão grato por nossa amizade.",
      message_type: "Amizade",
      recipient: 20,
      sender: 12,
    },
    {
      message: "Você merece todas as coisas boas que o mundo tem a oferecer.",
      message_type: "Motivacional",
      recipient: 53,
      sender: 13,
    },
    {
      message: "Hoje é um ótimo dia para ser incrível!",
      message_type: "Motivacional",
      recipient: 5,
      sender: 14,
    },
    {
      message: "Sua presença é o que torna tudo melhor.",
      message_type: "Romântica",
      recipient: 8,
      sender: 15,
    },
    {
      message: "Nada é impossível para quem tem determinação.",
      message_type: "Motivacional",
      recipient: 1,
      sender: 16,
    },
    {
      message: "Você é uma pessoa maravilhosa e merece todo sucesso.",
      message_type: "Motivacional",
      recipient: 60,
      sender: 17,
    },
    {
      message: "Nunca subestime o poder de um sorriso.",
      message_type: "Motivacional",
      recipient: 88,
      sender: 18,
    },
    {
      message: "Eu sempre vou estar aqui para você.",
      message_type: "Amizade",
      recipient: 66,
      sender: 19,
    },
    {
      message: "Nada como um bom papo com você.",
      message_type: "Amizade",
      recipient: 81,
      sender: 20,
    },
    {
      message: "Você me faz ver o mundo de uma forma mais leve.",
      message_type: "Romântica",
      recipient: 35,
      sender: 21,
    },
    {
      message: "Seu jeito de ser me encanta.",
      message_type: "Romântica",
      recipient: 40,
      sender: 22,
    },
    {
      message: "Não existe ninguém mais especial que você.",
      message_type: "Romântica",
      recipient: 27,
      sender: 23,
    },
    {
      message: "Você tem a capacidade de tornar o mundo um lugar melhor.",
      message_type: "Motivacional",
      recipient: 36,
      sender: 24,
    },
    {
      message: "Sempre que penso em você, sorrio.",
      message_type: "Romântica",
      recipient: 59,
      sender: 25,
    },
    {
      message: "A sua amizade é um presente que nunca vou deixar de valorizar.",
      message_type: "Amizade",
      recipient: 49,
      sender: 26,
    },
    {
      message: "Você é muito mais forte do que imagina.",
      message_type: "Motivacional",
      recipient: 12,
      sender: 27,
    },
    {
      message: "Sua determinação é admirável.",
      message_type: "Motivacional",
      recipient: 41,
      sender: 28,
    },
    {
      message: "O que você faz não é fácil, mas a sua coragem é inspiradora.",
      message_type: "Motivacional",
      recipient: 66,
      sender: 29,
    },
    {
      message: "A amizade verdadeira é rara, e eu tenho a sorte de ter a sua.",
      message_type: "Amizade",
      recipient: 13,
      sender: 30,
    },
    {
      message: "Cada dia com você é um dia incrível.",
      message_type: "Romântica",
      recipient: 46,
      sender: 31,
    },
    {
      message: "Você sempre me faz rir quando mais preciso.",
      message_type: "Comédia",
      recipient: 55,
      sender: 32,
    },
    {
      message: "Eu sou grato por todas as risadas que compartilhamos.",
      message_type: "Amizade",
      recipient: 47,
      sender: 33,
    },
    {
      message: "Nada é mais belo do que a sua visão do mundo.",
      message_type: "Romântica",
      recipient: 78,
      sender: 34,
    },
    {
      message:
        "Você consegue ser sério e engraçado ao mesmo tempo, e isso é uma arte.",
      message_type: "Comédia",
      recipient: 70,
      sender: 35,
    },
    {
      message: "Você tem um coração puro, e isso é raro.",
      message_type: "Motivacional",
      recipient: 38,
      sender: 36,
    },
    {
      message: "Amigos são o melhor remédio. E você é meu curativo favorito.",
      message_type: "Amizade",
      recipient: 56,
      sender: 37,
    },
    {
      message: "Com você ao meu lado, todo desafio parece pequeno.",
      message_type: "Motivacional",
      recipient: 4,
      sender: 38,
    },
    {
      message: "A vida é uma festa quando você está por perto.",
      message_type: "Comédia",
      recipient: 75,
      sender: 39,
    },
    {
      message: "Seu sorriso ilumina a sala inteira.",
      message_type: "Romântica",
      recipient: 53,
      sender: 40,
    },
    {
      message:
        "Você tem a incrível habilidade de fazer qualquer dia mais feliz.",
      message_type: "Motivacional",
      recipient: 32,
      sender: 41,
    },
    {
      message: "Eu me sinto sortudo por ter você na minha vida.",
      message_type: "Amizade",
      recipient: 64,
      sender: 42,
    },
    {
      message: "Às vezes, tudo o que a gente precisa é de um amigo como você.",
      message_type: "Amizade",
      recipient: 85,
      sender: 43,
    },
    {
      message: "Com você, tudo fica mais leve.",
      message_type: "Romântica",
      recipient: 51,
      sender: 44,
    },
    {
      message: "Não importa o que aconteça, vou sempre apoiar você.",
      message_type: "Motivacional",
      recipient: 63,
      sender: 45,
    },
    {
      message:
        "Sua risada é contagiante e me faz esquecer de todos os problemas.",
      message_type: "Comédia",
      recipient: 54,
      sender: 46,
    },
    {
      message: "Você me entende de uma forma única.",
      message_type: "Amizade",
      recipient: 73,
      sender: 47,
    },
    {
      message: "Seu brilho ilumina meu caminho.",
      message_type: "Romântica",
      recipient: 79,
      sender: 48,
    },
    {
      message: "A sua amizade me ajuda a ser uma pessoa melhor.",
      message_type: "Amizade",
      recipient: 84,
      sender: 49,
    },
    {
      message: "Nada é mais bonito do que ver você se realizando.",
      message_type: "Motivacional",
      recipient: 100,
      sender: 50,
    },
    {
      message:
        "Você é como uma estrela: sempre brilha, não importa a situação.",
      message_type: "Motivacional",
      recipient: 60,
      sender: 51,
    },
    {
      message: "Eu me sinto inspirado pela sua força e determinação.",
      message_type: "Motivacional",
      recipient: 21,
      sender: 52,
    },
    {
      message: "Você me faz querer ser uma pessoa melhor todos os dias.",
      message_type: "Motivacional",
      recipient: 24,
      sender: 53,
    },
    {
      message: "Você tem uma maneira única de ver o mundo e isso é incrível.",
      message_type: "Reflexiva",
      recipient: 39,
      sender: 54,
    },
    {
      message: "Com você, a vida é mais doce.",
      message_type: "Romântica",
      recipient: 69,
      sender: 55,
    },
    {
      message: "Nunca perca sua essência.",
      message_type: "Motivacional",
      recipient: 92,
      sender: 56,
    },
    {
      message:
        "Toda vez que você fala, todos prestam atenção. Você tem algo único em sua voz.",
      message_type: "Reflexiva",
      recipient: 14,
      sender: 57,
    },
    {
      message: "Você é uma pessoa incrível e merece o mundo.",
      message_type: "Motivacional",
      recipient: 53,
      sender: 58,
    },
    {
      message: "A forma como você pensa me inspira.",
      message_type: "Reflexiva",
      recipient: 56,
      sender: 59,
    },
    {
      message: "Você tem o dom de fazer com que tudo pareça mais fácil.",
      message_type: "Motivacional",
      recipient: 38,
      sender: 60,
    },
    {
      message: "Você é a pessoa mais divertida que eu conheço.",
      message_type: "Comédia",
      recipient: 12,
      sender: 61,
    },
    {
      message: "Com você, os dias nublados viram dias de sol.",
      message_type: "Romântica",
      recipient: 29,
      sender: 62,
    },
    {
      message: "Sua presença faz toda a diferença na minha vida.",
      message_type: "Romântica",
      recipient: 18,
      sender: 63,
    },
    {
      message: "Seu senso de humor é inigualável.",
      message_type: "Comédia",
      recipient: 2,
      sender: 64,
    },
    {
      message: "Seus olhos refletem toda a beleza do mundo.",
      message_type: "Romântica",
      recipient: 73,
      sender: 65,
    },
    {
      message: "Com você, as palavras ganham mais sentido.",
      message_type: "Reflexiva",
      recipient: 45,
      sender: 66,
    },
    {
      message: "Nada é mais importante do que as risadas que compartilhamos.",
      message_type: "Comédia",
      recipient: 51,
      sender: 67,
    },
    {
      message: "Sua amizade é uma verdadeira bênção na minha vida.",
      message_type: "Amizade",
      recipient: 31,
      sender: 68,
    },
    {
      message: "Eu sou muito grato pela pessoa maravilhosa que você é.",
      message_type: "Motivacional",
      recipient: 67,
      sender: 69,
    },
    {
      message:
        "Eu adoro a forma como você sempre se esforça para fazer os outros sorrirem.",
      message_type: "Comédia",
      recipient: 55,
      sender: 70,
    },
    {
      message: "Toda vez que você sorri, o mundo parece mais bonito.",
      message_type: "Romântica",
      recipient: 59,
      sender: 71,
    },
    {
      message: "Nunca pare de ser quem você é.",
      message_type: "Motivacional",
      recipient: 43,
      sender: 72,
    },
    {
      message: "Sua amizade é a coisa mais valiosa que eu tenho.",
      message_type: "Amizade",
      recipient: 92,
      sender: 73,
    },
    {
      message: "Você sempre faz minha vida mais alegre.",
      message_type: "Comédia",
      recipient: 87,
      sender: 74,
    },
    {
      message: "Eu sou grato por sua amizade todos os dias.",
      message_type: "Amizade",
      recipient: 33,
      sender: 75,
    },
    {
      message: "Você é muito mais forte do que você imagina.",
      message_type: "Motivacional",
      recipient: 28,
      sender: 76,
    },
    {
      message: "A sua amizade é o meu maior tesouro.",
      message_type: "Amizade",
      recipient: 12,
      sender: 77,
    },
    {
      message: "Nunca perca a sua capacidade de sonhar.",
      message_type: "Motivacional",
      recipient: 80,
      sender: 78,
    },
    {
      message: "Cada momento com você é um presente.",
      message_type: "Romântica",
      recipient: 61,
      sender: 79,
    },
    {
      message: "A amizade verdadeira é eterna, como a nossa.",
      message_type: "Amizade",
      recipient: 17,
      sender: 80,
    },
    {
      message:
        "Você tem o poder de transformar qualquer dia ruim em um bom dia.",
      message_type: "Motivacional",
      recipient: 73,
      sender: 81,
    },
    {
      message: "Eu sou uma pessoa melhor por ter você na minha vida.",
      message_type: "Motivacional",
      recipient: 52,
      sender: 82,
    },
    {
      message: "Você faz com que tudo ao seu redor pareça mais bonito.",
      message_type: "Romântica",
      recipient: 46,
      sender: 83,
    },
    {
      message: "Sua confiança é inspiradora.",
      message_type: "Motivacional",
      recipient: 30,
      sender: 84,
    },
    {
      message: "Cada sorriso seu é como um raio de sol.",
      message_type: "Romântica",
      recipient: 61,
      sender: 85,
    },
    {
      message: "Com você, não há limites para o que podemos conquistar.",
      message_type: "Motivacional",
      recipient: 87,
      sender: 86,
    },
    {
      message:
        "Você tem um talento incrível para fazer os outros se sentirem especiais.",
      message_type: "Comédia",
      recipient: 51,
      sender: 87,
    },
    {
      message: "Sua presença é sempre uma alegria.",
      message_type: "Amizade",
      recipient: 55,
      sender: 88,
    },
    {
      message: "Seu jeito único de ser me fascina.",
      message_type: "Romântica",
      recipient: 69,
      sender: 89,
    },
    {
      message: "Você me ensina todos os dias a ser melhor.",
      message_type: "Motivacional",
      recipient: 32,
      sender: 90,
    },
    {
      message: "Você é minha fonte de inspiração.",
      message_type: "Motivacional",
      recipient: 66,
      sender: 91,
    },
    {
      message: "Sua risada é o melhor som que eu já ouvi.",
      message_type: "Comédia",
      recipient: 56,
      sender: 92,
    },
    {
      message: "Você é um presente para o mundo.",
      message_type: "Motivacional",
      recipient: 81,
      sender: 93,
    },
    {
      message: "Eu sou grato por cada segundo ao seu lado.",
      message_type: "Romântica",
      recipient: 87,
      sender: 94,
    },
    {
      message: "Sempre que estou perto de você, o tempo parece parar.",
      message_type: "Romântica",
      recipient: 56,
      sender: 95,
    },
    {
      message: "Sua amizade é o maior tesouro que eu poderia pedir.",
      message_type: "Amizade",
      recipient: 39,
      sender: 96,
    },
    {
      message: "Você sempre sabe como me fazer sorrir.",
      message_type: "Comédia",
      recipient: 71,
      sender: 97,
    },
    {
      message: "Eu nunca vou deixar de apoiar você.",
      message_type: "Motivacional",
      recipient: 47,
      sender: 98,
    },
    {
      message: "Você é uma pessoa com um coração gigante.",
      message_type: "Motivacional",
      recipient: 73,
      sender: 99,
    },
    {
      message: "Eu sou muito grato por tudo o que você faz.",
      message_type: "Motivacional",
      recipient: 38,
      sender: 100,
    },
  ];

  await prisma.users.createMany({
    data: users,
    skipDuplicates: true,
  });

  await prisma.confessions.createMany({
    data: confessions,
    skipDuplicates: true,
  });

  console.log("O seed foi executado com sucesso 👍");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
